[package]
name = "chip8-rom-to-opcod"
version = "0.1.0"
authors = ["NickPerrin <perrin.64@osu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
